#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : dpdk
Version  : 18.11.1
Release  : 41
URL      : http://fast.dpdk.org/rel/dpdk-18.11.1.tar.xz
Source0  : http://fast.dpdk.org/rel/dpdk-18.11.1.tar.xz
Summary  : Data Plane Development Kit core
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.0
Requires: dpdk-bin = %{version}-%{release}
Requires: dpdk-data = %{version}-%{release}
Requires: dpdk-lib = %{version}-%{release}
BuildRequires : buildreq-meson
BuildRequires : libpcap-dev
BuildRequires : numactl-dev
Patch1: 0001-disable-dpdk-kernel-modules.patch
Patch2: 0002-enable-dpdk-shared-libs.patch
Patch3: no-arch-native.patch

%description
DPDK core includes kernel modules, core libraries and tools.
testpmd application allows to test fast packet processing environments
on x86 platforms. For instance, it can be used to check that environment
can support fast path applications such as 6WINDGate, pktgen, rumptcpip, etc.
More libraries are available as extensions in other packages.

%package bin
Summary: bin components for the dpdk package.
Group: Binaries
Requires: dpdk-data = %{version}-%{release}

%description bin
bin components for the dpdk package.


%package data
Summary: data components for the dpdk package.
Group: Data

%description data
data components for the dpdk package.


%package dev
Summary: dev components for the dpdk package.
Group: Development
Requires: dpdk-lib = %{version}-%{release}
Requires: dpdk-bin = %{version}-%{release}
Requires: dpdk-data = %{version}-%{release}
Provides: dpdk-devel = %{version}-%{release}
Requires: dpdk = %{version}-%{release}

%description dev
dev components for the dpdk package.


%package lib
Summary: lib components for the dpdk package.
Group: Libraries
Requires: dpdk-data = %{version}-%{release}

%description lib
lib components for the dpdk package.


%prep
%setup -q -n dpdk-stable-18.11.1
%patch1 -p1
%patch2 -p1
%patch3 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1555655368
export LDFLAGS="${LDFLAGS} -fno-lto"
make  %{?_smp_mflags} config T=x86_64-native-linuxapp-gcc; make V=1


%install
export SOURCE_DATE_EPOCH=1555655368
rm -rf %{buildroot}
%make_install prefix=/usr libdir=/usr/lib64 includedir=/usr/include

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/dpdk-devbind
/usr/bin/dpdk-pdump
/usr/bin/dpdk-pmdinfo
/usr/bin/dpdk-procinfo
/usr/bin/dpdk-test-crypto-perf
/usr/bin/dpdk-test-eventdev
/usr/bin/testbbdev
/usr/bin/testpmd

%files data
%defattr(-,root,root,-)
%exclude /usr/share/dpdk/x86_64-native-linuxapp-gcc/include
%exclude /usr/share/dpdk/x86_64-native-linuxapp-gcc/lib
/usr/share/dpdk/buildtools/Makefile
/usr/share/dpdk/buildtools/auto-config-h.sh
/usr/share/dpdk/buildtools/check-experimental-syms.sh
/usr/share/dpdk/buildtools/gen-build-mk.sh
/usr/share/dpdk/buildtools/gen-config-h.sh
/usr/share/dpdk/buildtools/gen-pmdinfo-cfile.sh
/usr/share/dpdk/buildtools/meson.build
/usr/share/dpdk/buildtools/pmdinfogen/Makefile
/usr/share/dpdk/buildtools/pmdinfogen/meson.build
/usr/share/dpdk/buildtools/pmdinfogen/pmdinfogen.c
/usr/share/dpdk/buildtools/pmdinfogen/pmdinfogen.h
/usr/share/dpdk/buildtools/relpath.sh
/usr/share/dpdk/buildtools/symlink-drivers-solibs.sh
/usr/share/dpdk/examples/Makefile
/usr/share/dpdk/examples/bbdev_app/Makefile
/usr/share/dpdk/examples/bbdev_app/main.c
/usr/share/dpdk/examples/bbdev_app/meson.build
/usr/share/dpdk/examples/bond/Makefile
/usr/share/dpdk/examples/bond/main.c
/usr/share/dpdk/examples/bond/main.h
/usr/share/dpdk/examples/bond/meson.build
/usr/share/dpdk/examples/cmdline/Makefile
/usr/share/dpdk/examples/cmdline/commands.c
/usr/share/dpdk/examples/cmdline/commands.h
/usr/share/dpdk/examples/cmdline/main.c
/usr/share/dpdk/examples/cmdline/meson.build
/usr/share/dpdk/examples/cmdline/parse_obj_list.c
/usr/share/dpdk/examples/cmdline/parse_obj_list.h
/usr/share/dpdk/examples/distributor/Makefile
/usr/share/dpdk/examples/distributor/main.c
/usr/share/dpdk/examples/distributor/meson.build
/usr/share/dpdk/examples/ethtool/Makefile
/usr/share/dpdk/examples/ethtool/ethtool-app/Makefile
/usr/share/dpdk/examples/ethtool/ethtool-app/ethapp.c
/usr/share/dpdk/examples/ethtool/ethtool-app/ethapp.h
/usr/share/dpdk/examples/ethtool/ethtool-app/main.c
/usr/share/dpdk/examples/ethtool/lib/Makefile
/usr/share/dpdk/examples/ethtool/lib/rte_ethtool.c
/usr/share/dpdk/examples/ethtool/lib/rte_ethtool.h
/usr/share/dpdk/examples/ethtool/meson.build
/usr/share/dpdk/examples/eventdev_pipeline/Makefile
/usr/share/dpdk/examples/eventdev_pipeline/main.c
/usr/share/dpdk/examples/eventdev_pipeline/meson.build
/usr/share/dpdk/examples/eventdev_pipeline/pipeline_common.h
/usr/share/dpdk/examples/eventdev_pipeline/pipeline_worker_generic.c
/usr/share/dpdk/examples/eventdev_pipeline/pipeline_worker_tx.c
/usr/share/dpdk/examples/exception_path/Makefile
/usr/share/dpdk/examples/exception_path/main.c
/usr/share/dpdk/examples/exception_path/meson.build
/usr/share/dpdk/examples/fips_validation/Makefile
/usr/share/dpdk/examples/fips_validation/fips_validation.c
/usr/share/dpdk/examples/fips_validation/fips_validation.h
/usr/share/dpdk/examples/fips_validation/fips_validation_aes.c
/usr/share/dpdk/examples/fips_validation/fips_validation_ccm.c
/usr/share/dpdk/examples/fips_validation/fips_validation_cmac.c
/usr/share/dpdk/examples/fips_validation/fips_validation_gcm.c
/usr/share/dpdk/examples/fips_validation/fips_validation_hmac.c
/usr/share/dpdk/examples/fips_validation/fips_validation_tdes.c
/usr/share/dpdk/examples/fips_validation/main.c
/usr/share/dpdk/examples/fips_validation/meson.build
/usr/share/dpdk/examples/flow_classify/Makefile
/usr/share/dpdk/examples/flow_classify/flow_classify.c
/usr/share/dpdk/examples/flow_classify/ipv4_rules_file.txt
/usr/share/dpdk/examples/flow_classify/meson.build
/usr/share/dpdk/examples/flow_filtering/Makefile
/usr/share/dpdk/examples/flow_filtering/flow_blocks.c
/usr/share/dpdk/examples/flow_filtering/main.c
/usr/share/dpdk/examples/flow_filtering/meson.build
/usr/share/dpdk/examples/helloworld/Makefile
/usr/share/dpdk/examples/helloworld/main.c
/usr/share/dpdk/examples/helloworld/meson.build
/usr/share/dpdk/examples/ip_fragmentation/Makefile
/usr/share/dpdk/examples/ip_fragmentation/main.c
/usr/share/dpdk/examples/ip_fragmentation/meson.build
/usr/share/dpdk/examples/ip_pipeline/Makefile
/usr/share/dpdk/examples/ip_pipeline/action.c
/usr/share/dpdk/examples/ip_pipeline/action.h
/usr/share/dpdk/examples/ip_pipeline/cli.c
/usr/share/dpdk/examples/ip_pipeline/cli.h
/usr/share/dpdk/examples/ip_pipeline/common.h
/usr/share/dpdk/examples/ip_pipeline/conn.c
/usr/share/dpdk/examples/ip_pipeline/conn.h
/usr/share/dpdk/examples/ip_pipeline/cryptodev.c
/usr/share/dpdk/examples/ip_pipeline/cryptodev.h
/usr/share/dpdk/examples/ip_pipeline/examples/firewall.cli
/usr/share/dpdk/examples/ip_pipeline/examples/flow.cli
/usr/share/dpdk/examples/ip_pipeline/examples/flow_crypto.cli
/usr/share/dpdk/examples/ip_pipeline/examples/kni.cli
/usr/share/dpdk/examples/ip_pipeline/examples/l2fwd.cli
/usr/share/dpdk/examples/ip_pipeline/examples/route.cli
/usr/share/dpdk/examples/ip_pipeline/examples/route_ecmp.cli
/usr/share/dpdk/examples/ip_pipeline/examples/rss.cli
/usr/share/dpdk/examples/ip_pipeline/examples/tap.cli
/usr/share/dpdk/examples/ip_pipeline/kni.c
/usr/share/dpdk/examples/ip_pipeline/kni.h
/usr/share/dpdk/examples/ip_pipeline/link.c
/usr/share/dpdk/examples/ip_pipeline/link.h
/usr/share/dpdk/examples/ip_pipeline/main.c
/usr/share/dpdk/examples/ip_pipeline/mempool.c
/usr/share/dpdk/examples/ip_pipeline/mempool.h
/usr/share/dpdk/examples/ip_pipeline/meson.build
/usr/share/dpdk/examples/ip_pipeline/parser.c
/usr/share/dpdk/examples/ip_pipeline/parser.h
/usr/share/dpdk/examples/ip_pipeline/pipeline.c
/usr/share/dpdk/examples/ip_pipeline/pipeline.h
/usr/share/dpdk/examples/ip_pipeline/swq.c
/usr/share/dpdk/examples/ip_pipeline/swq.h
/usr/share/dpdk/examples/ip_pipeline/tap.c
/usr/share/dpdk/examples/ip_pipeline/tap.h
/usr/share/dpdk/examples/ip_pipeline/thread.c
/usr/share/dpdk/examples/ip_pipeline/thread.h
/usr/share/dpdk/examples/ip_pipeline/tmgr.c
/usr/share/dpdk/examples/ip_pipeline/tmgr.h
/usr/share/dpdk/examples/ip_reassembly/Makefile
/usr/share/dpdk/examples/ip_reassembly/main.c
/usr/share/dpdk/examples/ip_reassembly/meson.build
/usr/share/dpdk/examples/ipsec-secgw/Makefile
/usr/share/dpdk/examples/ipsec-secgw/ep0.cfg
/usr/share/dpdk/examples/ipsec-secgw/ep1.cfg
/usr/share/dpdk/examples/ipsec-secgw/esp.c
/usr/share/dpdk/examples/ipsec-secgw/esp.h
/usr/share/dpdk/examples/ipsec-secgw/ipip.h
/usr/share/dpdk/examples/ipsec-secgw/ipsec-secgw.c
/usr/share/dpdk/examples/ipsec-secgw/ipsec.c
/usr/share/dpdk/examples/ipsec-secgw/ipsec.h
/usr/share/dpdk/examples/ipsec-secgw/meson.build
/usr/share/dpdk/examples/ipsec-secgw/parser.c
/usr/share/dpdk/examples/ipsec-secgw/parser.h
/usr/share/dpdk/examples/ipsec-secgw/rt.c
/usr/share/dpdk/examples/ipsec-secgw/sa.c
/usr/share/dpdk/examples/ipsec-secgw/sp4.c
/usr/share/dpdk/examples/ipsec-secgw/sp6.c
/usr/share/dpdk/examples/ipv4_multicast/Makefile
/usr/share/dpdk/examples/ipv4_multicast/main.c
/usr/share/dpdk/examples/ipv4_multicast/meson.build
/usr/share/dpdk/examples/kni/Makefile
/usr/share/dpdk/examples/kni/main.c
/usr/share/dpdk/examples/kni/meson.build
/usr/share/dpdk/examples/l2fwd-cat/Makefile
/usr/share/dpdk/examples/l2fwd-cat/cat.c
/usr/share/dpdk/examples/l2fwd-cat/cat.h
/usr/share/dpdk/examples/l2fwd-cat/l2fwd-cat.c
/usr/share/dpdk/examples/l2fwd-cat/meson.build
/usr/share/dpdk/examples/l2fwd-crypto/Makefile
/usr/share/dpdk/examples/l2fwd-crypto/main.c
/usr/share/dpdk/examples/l2fwd-crypto/meson.build
/usr/share/dpdk/examples/l2fwd-jobstats/Makefile
/usr/share/dpdk/examples/l2fwd-jobstats/main.c
/usr/share/dpdk/examples/l2fwd-jobstats/meson.build
/usr/share/dpdk/examples/l2fwd-keepalive/Makefile
/usr/share/dpdk/examples/l2fwd-keepalive/ka-agent/Makefile
/usr/share/dpdk/examples/l2fwd-keepalive/ka-agent/main.c
/usr/share/dpdk/examples/l2fwd-keepalive/main.c
/usr/share/dpdk/examples/l2fwd-keepalive/meson.build
/usr/share/dpdk/examples/l2fwd-keepalive/shm.c
/usr/share/dpdk/examples/l2fwd-keepalive/shm.h
/usr/share/dpdk/examples/l2fwd/Makefile
/usr/share/dpdk/examples/l2fwd/main.c
/usr/share/dpdk/examples/l2fwd/meson.build
/usr/share/dpdk/examples/l3fwd-acl/Makefile
/usr/share/dpdk/examples/l3fwd-acl/main.c
/usr/share/dpdk/examples/l3fwd-acl/meson.build
/usr/share/dpdk/examples/l3fwd-power/Makefile
/usr/share/dpdk/examples/l3fwd-power/main.c
/usr/share/dpdk/examples/l3fwd-power/main.h
/usr/share/dpdk/examples/l3fwd-power/meson.build
/usr/share/dpdk/examples/l3fwd-power/perf_core.c
/usr/share/dpdk/examples/l3fwd-power/perf_core.h
/usr/share/dpdk/examples/l3fwd-vf/Makefile
/usr/share/dpdk/examples/l3fwd-vf/main.c
/usr/share/dpdk/examples/l3fwd-vf/meson.build
/usr/share/dpdk/examples/l3fwd/Makefile
/usr/share/dpdk/examples/l3fwd/l3fwd.h
/usr/share/dpdk/examples/l3fwd/l3fwd_altivec.h
/usr/share/dpdk/examples/l3fwd/l3fwd_common.h
/usr/share/dpdk/examples/l3fwd/l3fwd_em.c
/usr/share/dpdk/examples/l3fwd/l3fwd_em.h
/usr/share/dpdk/examples/l3fwd/l3fwd_em_hlm.h
/usr/share/dpdk/examples/l3fwd/l3fwd_em_hlm_neon.h
/usr/share/dpdk/examples/l3fwd/l3fwd_em_hlm_sse.h
/usr/share/dpdk/examples/l3fwd/l3fwd_em_sequential.h
/usr/share/dpdk/examples/l3fwd/l3fwd_lpm.c
/usr/share/dpdk/examples/l3fwd/l3fwd_lpm.h
/usr/share/dpdk/examples/l3fwd/l3fwd_lpm_altivec.h
/usr/share/dpdk/examples/l3fwd/l3fwd_lpm_neon.h
/usr/share/dpdk/examples/l3fwd/l3fwd_lpm_sse.h
/usr/share/dpdk/examples/l3fwd/l3fwd_neon.h
/usr/share/dpdk/examples/l3fwd/l3fwd_sse.h
/usr/share/dpdk/examples/l3fwd/main.c
/usr/share/dpdk/examples/l3fwd/meson.build
/usr/share/dpdk/examples/link_status_interrupt/Makefile
/usr/share/dpdk/examples/link_status_interrupt/main.c
/usr/share/dpdk/examples/link_status_interrupt/meson.build
/usr/share/dpdk/examples/load_balancer/Makefile
/usr/share/dpdk/examples/load_balancer/config.c
/usr/share/dpdk/examples/load_balancer/init.c
/usr/share/dpdk/examples/load_balancer/main.c
/usr/share/dpdk/examples/load_balancer/main.h
/usr/share/dpdk/examples/load_balancer/meson.build
/usr/share/dpdk/examples/load_balancer/runtime.c
/usr/share/dpdk/examples/meson.build
/usr/share/dpdk/examples/multi_process/Makefile
/usr/share/dpdk/examples/multi_process/client_server_mp/Makefile
/usr/share/dpdk/examples/multi_process/client_server_mp/mp_client/Makefile
/usr/share/dpdk/examples/multi_process/client_server_mp/mp_client/client.c
/usr/share/dpdk/examples/multi_process/client_server_mp/mp_server/Makefile
/usr/share/dpdk/examples/multi_process/client_server_mp/mp_server/args.c
/usr/share/dpdk/examples/multi_process/client_server_mp/mp_server/args.h
/usr/share/dpdk/examples/multi_process/client_server_mp/mp_server/init.c
/usr/share/dpdk/examples/multi_process/client_server_mp/mp_server/init.h
/usr/share/dpdk/examples/multi_process/client_server_mp/mp_server/main.c
/usr/share/dpdk/examples/multi_process/client_server_mp/shared/common.h
/usr/share/dpdk/examples/multi_process/hotplug_mp/Makefile
/usr/share/dpdk/examples/multi_process/hotplug_mp/commands.c
/usr/share/dpdk/examples/multi_process/hotplug_mp/commands.h
/usr/share/dpdk/examples/multi_process/hotplug_mp/main.c
/usr/share/dpdk/examples/multi_process/meson.build
/usr/share/dpdk/examples/multi_process/simple_mp/Makefile
/usr/share/dpdk/examples/multi_process/simple_mp/main.c
/usr/share/dpdk/examples/multi_process/simple_mp/mp_commands.c
/usr/share/dpdk/examples/multi_process/simple_mp/mp_commands.h
/usr/share/dpdk/examples/multi_process/symmetric_mp/Makefile
/usr/share/dpdk/examples/multi_process/symmetric_mp/main.c
/usr/share/dpdk/examples/netmap_compat/Makefile
/usr/share/dpdk/examples/netmap_compat/bridge/Makefile
/usr/share/dpdk/examples/netmap_compat/bridge/bridge.c
/usr/share/dpdk/examples/netmap_compat/lib/compat_netmap.c
/usr/share/dpdk/examples/netmap_compat/lib/compat_netmap.h
/usr/share/dpdk/examples/netmap_compat/meson.build
/usr/share/dpdk/examples/netmap_compat/netmap/netmap.h
/usr/share/dpdk/examples/netmap_compat/netmap/netmap_user.h
/usr/share/dpdk/examples/packet_ordering/Makefile
/usr/share/dpdk/examples/packet_ordering/main.c
/usr/share/dpdk/examples/packet_ordering/meson.build
/usr/share/dpdk/examples/performance-thread/Makefile
/usr/share/dpdk/examples/performance-thread/common/arch/arm64/ctx.c
/usr/share/dpdk/examples/performance-thread/common/arch/arm64/ctx.h
/usr/share/dpdk/examples/performance-thread/common/arch/arm64/stack.h
/usr/share/dpdk/examples/performance-thread/common/arch/x86/ctx.c
/usr/share/dpdk/examples/performance-thread/common/arch/x86/ctx.h
/usr/share/dpdk/examples/performance-thread/common/arch/x86/stack.h
/usr/share/dpdk/examples/performance-thread/common/common.mk
/usr/share/dpdk/examples/performance-thread/common/lthread.c
/usr/share/dpdk/examples/performance-thread/common/lthread.h
/usr/share/dpdk/examples/performance-thread/common/lthread_api.h
/usr/share/dpdk/examples/performance-thread/common/lthread_cond.c
/usr/share/dpdk/examples/performance-thread/common/lthread_cond.h
/usr/share/dpdk/examples/performance-thread/common/lthread_diag.c
/usr/share/dpdk/examples/performance-thread/common/lthread_diag.h
/usr/share/dpdk/examples/performance-thread/common/lthread_diag_api.h
/usr/share/dpdk/examples/performance-thread/common/lthread_int.h
/usr/share/dpdk/examples/performance-thread/common/lthread_mutex.c
/usr/share/dpdk/examples/performance-thread/common/lthread_mutex.h
/usr/share/dpdk/examples/performance-thread/common/lthread_objcache.h
/usr/share/dpdk/examples/performance-thread/common/lthread_pool.h
/usr/share/dpdk/examples/performance-thread/common/lthread_queue.h
/usr/share/dpdk/examples/performance-thread/common/lthread_sched.c
/usr/share/dpdk/examples/performance-thread/common/lthread_sched.h
/usr/share/dpdk/examples/performance-thread/common/lthread_timer.h
/usr/share/dpdk/examples/performance-thread/common/lthread_tls.c
/usr/share/dpdk/examples/performance-thread/common/lthread_tls.h
/usr/share/dpdk/examples/performance-thread/l3fwd-thread/Makefile
/usr/share/dpdk/examples/performance-thread/l3fwd-thread/main.c
/usr/share/dpdk/examples/performance-thread/l3fwd-thread/test.sh
/usr/share/dpdk/examples/performance-thread/meson.build
/usr/share/dpdk/examples/performance-thread/pthread_shim/Makefile
/usr/share/dpdk/examples/performance-thread/pthread_shim/main.c
/usr/share/dpdk/examples/performance-thread/pthread_shim/pthread_shim.c
/usr/share/dpdk/examples/performance-thread/pthread_shim/pthread_shim.h
/usr/share/dpdk/examples/ptpclient/Makefile
/usr/share/dpdk/examples/ptpclient/meson.build
/usr/share/dpdk/examples/ptpclient/ptpclient.c
/usr/share/dpdk/examples/qos_meter/Makefile
/usr/share/dpdk/examples/qos_meter/main.c
/usr/share/dpdk/examples/qos_meter/main.h
/usr/share/dpdk/examples/qos_meter/meson.build
/usr/share/dpdk/examples/qos_meter/rte_policer.c
/usr/share/dpdk/examples/qos_meter/rte_policer.h
/usr/share/dpdk/examples/qos_sched/Makefile
/usr/share/dpdk/examples/qos_sched/app_thread.c
/usr/share/dpdk/examples/qos_sched/args.c
/usr/share/dpdk/examples/qos_sched/cfg_file.c
/usr/share/dpdk/examples/qos_sched/cfg_file.h
/usr/share/dpdk/examples/qos_sched/cmdline.c
/usr/share/dpdk/examples/qos_sched/init.c
/usr/share/dpdk/examples/qos_sched/main.c
/usr/share/dpdk/examples/qos_sched/main.h
/usr/share/dpdk/examples/qos_sched/meson.build
/usr/share/dpdk/examples/qos_sched/profile.cfg
/usr/share/dpdk/examples/qos_sched/profile_ov.cfg
/usr/share/dpdk/examples/qos_sched/stats.c
/usr/share/dpdk/examples/quota_watermark/Makefile
/usr/share/dpdk/examples/quota_watermark/meson.build
/usr/share/dpdk/examples/quota_watermark/qw/Makefile
/usr/share/dpdk/examples/quota_watermark/qw/args.c
/usr/share/dpdk/examples/quota_watermark/qw/args.h
/usr/share/dpdk/examples/quota_watermark/qw/init.c
/usr/share/dpdk/examples/quota_watermark/qw/init.h
/usr/share/dpdk/examples/quota_watermark/qw/main.c
/usr/share/dpdk/examples/quota_watermark/qw/main.h
/usr/share/dpdk/examples/quota_watermark/qwctl/Makefile
/usr/share/dpdk/examples/quota_watermark/qwctl/commands.c
/usr/share/dpdk/examples/quota_watermark/qwctl/commands.h
/usr/share/dpdk/examples/quota_watermark/qwctl/qwctl.c
/usr/share/dpdk/examples/quota_watermark/qwctl/qwctl.h
/usr/share/dpdk/examples/rxtx_callbacks/Makefile
/usr/share/dpdk/examples/rxtx_callbacks/main.c
/usr/share/dpdk/examples/rxtx_callbacks/meson.build
/usr/share/dpdk/examples/server_node_efd/Makefile
/usr/share/dpdk/examples/server_node_efd/meson.build
/usr/share/dpdk/examples/server_node_efd/node/Makefile
/usr/share/dpdk/examples/server_node_efd/node/node.c
/usr/share/dpdk/examples/server_node_efd/server/Makefile
/usr/share/dpdk/examples/server_node_efd/server/args.c
/usr/share/dpdk/examples/server_node_efd/server/args.h
/usr/share/dpdk/examples/server_node_efd/server/init.c
/usr/share/dpdk/examples/server_node_efd/server/init.h
/usr/share/dpdk/examples/server_node_efd/server/main.c
/usr/share/dpdk/examples/server_node_efd/shared/common.h
/usr/share/dpdk/examples/service_cores/Makefile
/usr/share/dpdk/examples/service_cores/main.c
/usr/share/dpdk/examples/service_cores/meson.build
/usr/share/dpdk/examples/skeleton/Makefile
/usr/share/dpdk/examples/skeleton/basicfwd.c
/usr/share/dpdk/examples/skeleton/meson.build
/usr/share/dpdk/examples/tep_termination/Makefile
/usr/share/dpdk/examples/tep_termination/main.c
/usr/share/dpdk/examples/tep_termination/main.h
/usr/share/dpdk/examples/tep_termination/meson.build
/usr/share/dpdk/examples/tep_termination/vxlan.c
/usr/share/dpdk/examples/tep_termination/vxlan.h
/usr/share/dpdk/examples/tep_termination/vxlan_setup.c
/usr/share/dpdk/examples/tep_termination/vxlan_setup.h
/usr/share/dpdk/examples/timer/Makefile
/usr/share/dpdk/examples/timer/main.c
/usr/share/dpdk/examples/timer/meson.build
/usr/share/dpdk/examples/vdpa/Makefile
/usr/share/dpdk/examples/vdpa/main.c
/usr/share/dpdk/examples/vdpa/meson.build
/usr/share/dpdk/examples/vhost/Makefile
/usr/share/dpdk/examples/vhost/main.c
/usr/share/dpdk/examples/vhost/main.h
/usr/share/dpdk/examples/vhost/meson.build
/usr/share/dpdk/examples/vhost/virtio_net.c
/usr/share/dpdk/examples/vhost_crypto/Makefile
/usr/share/dpdk/examples/vhost_crypto/main.c
/usr/share/dpdk/examples/vhost_crypto/meson.build
/usr/share/dpdk/examples/vhost_scsi/Makefile
/usr/share/dpdk/examples/vhost_scsi/meson.build
/usr/share/dpdk/examples/vhost_scsi/scsi.c
/usr/share/dpdk/examples/vhost_scsi/scsi_spec.h
/usr/share/dpdk/examples/vhost_scsi/vhost_scsi.c
/usr/share/dpdk/examples/vhost_scsi/vhost_scsi.h
/usr/share/dpdk/examples/vm_power_manager/Makefile
/usr/share/dpdk/examples/vm_power_manager/channel_manager.c
/usr/share/dpdk/examples/vm_power_manager/channel_manager.h
/usr/share/dpdk/examples/vm_power_manager/channel_monitor.c
/usr/share/dpdk/examples/vm_power_manager/channel_monitor.h
/usr/share/dpdk/examples/vm_power_manager/guest_cli/Makefile
/usr/share/dpdk/examples/vm_power_manager/guest_cli/main.c
/usr/share/dpdk/examples/vm_power_manager/guest_cli/meson.build
/usr/share/dpdk/examples/vm_power_manager/guest_cli/parse.c
/usr/share/dpdk/examples/vm_power_manager/guest_cli/parse.h
/usr/share/dpdk/examples/vm_power_manager/guest_cli/vm_power_cli_guest.c
/usr/share/dpdk/examples/vm_power_manager/guest_cli/vm_power_cli_guest.h
/usr/share/dpdk/examples/vm_power_manager/main.c
/usr/share/dpdk/examples/vm_power_manager/meson.build
/usr/share/dpdk/examples/vm_power_manager/oob_monitor.h
/usr/share/dpdk/examples/vm_power_manager/oob_monitor_nop.c
/usr/share/dpdk/examples/vm_power_manager/oob_monitor_x86.c
/usr/share/dpdk/examples/vm_power_manager/parse.c
/usr/share/dpdk/examples/vm_power_manager/parse.h
/usr/share/dpdk/examples/vm_power_manager/power_manager.c
/usr/share/dpdk/examples/vm_power_manager/power_manager.h
/usr/share/dpdk/examples/vm_power_manager/vm_power_cli.c
/usr/share/dpdk/examples/vm_power_manager/vm_power_cli.h
/usr/share/dpdk/examples/vmdq/Makefile
/usr/share/dpdk/examples/vmdq/main.c
/usr/share/dpdk/examples/vmdq/meson.build
/usr/share/dpdk/examples/vmdq_dcb/Makefile
/usr/share/dpdk/examples/vmdq_dcb/main.c
/usr/share/dpdk/examples/vmdq_dcb/meson.build
/usr/share/dpdk/mk/arch/arm/rte.vars.mk
/usr/share/dpdk/mk/arch/arm64/rte.vars.mk
/usr/share/dpdk/mk/arch/i686/rte.vars.mk
/usr/share/dpdk/mk/arch/ppc_64/rte.vars.mk
/usr/share/dpdk/mk/arch/x86_64/rte.vars.mk
/usr/share/dpdk/mk/arch/x86_x32/rte.vars.mk
/usr/share/dpdk/mk/exec-env/bsdapp/rte.app.mk
/usr/share/dpdk/mk/exec-env/bsdapp/rte.vars.mk
/usr/share/dpdk/mk/exec-env/linuxapp/rte.app.mk
/usr/share/dpdk/mk/exec-env/linuxapp/rte.vars.mk
/usr/share/dpdk/mk/internal/rte.build-post.mk
/usr/share/dpdk/mk/internal/rte.build-pre.mk
/usr/share/dpdk/mk/internal/rte.clean-post.mk
/usr/share/dpdk/mk/internal/rte.clean-pre.mk
/usr/share/dpdk/mk/internal/rte.compile-post.mk
/usr/share/dpdk/mk/internal/rte.compile-pre.mk
/usr/share/dpdk/mk/internal/rte.extvars.mk
/usr/share/dpdk/mk/internal/rte.install-post.mk
/usr/share/dpdk/mk/internal/rte.install-pre.mk
/usr/share/dpdk/mk/machine/armv7a/rte.vars.mk
/usr/share/dpdk/mk/machine/armv8a/rte.vars.mk
/usr/share/dpdk/mk/machine/default/rte.vars.mk
/usr/share/dpdk/mk/machine/dpaa/rte.vars.mk
/usr/share/dpdk/mk/machine/dpaa2/rte.vars.mk
/usr/share/dpdk/mk/machine/hsw/rte.vars.mk
/usr/share/dpdk/mk/machine/ivb/rte.vars.mk
/usr/share/dpdk/mk/machine/native/rte.vars.mk
/usr/share/dpdk/mk/machine/native/rte.vars.mk.orig
/usr/share/dpdk/mk/machine/nhm/rte.vars.mk
/usr/share/dpdk/mk/machine/power8/rte.vars.mk
/usr/share/dpdk/mk/machine/silvermont/rte.vars.mk
/usr/share/dpdk/mk/machine/snb/rte.vars.mk
/usr/share/dpdk/mk/machine/thunderx/rte.vars.mk
/usr/share/dpdk/mk/machine/wsm/rte.vars.mk
/usr/share/dpdk/mk/machine/xgene1/rte.vars.mk
/usr/share/dpdk/mk/rte.app.mk
/usr/share/dpdk/mk/rte.bsdmodule.mk
/usr/share/dpdk/mk/rte.combinedlib.mk
/usr/share/dpdk/mk/rte.cpuflags.mk
/usr/share/dpdk/mk/rte.extapp.mk
/usr/share/dpdk/mk/rte.extlib.mk
/usr/share/dpdk/mk/rte.extobj.mk
/usr/share/dpdk/mk/rte.extshared.mk
/usr/share/dpdk/mk/rte.extsubdir.mk
/usr/share/dpdk/mk/rte.gnuconfigure.mk
/usr/share/dpdk/mk/rte.hostapp.mk
/usr/share/dpdk/mk/rte.hostlib.mk
/usr/share/dpdk/mk/rte.install.mk
/usr/share/dpdk/mk/rte.lib.mk
/usr/share/dpdk/mk/rte.module.mk
/usr/share/dpdk/mk/rte.obj.mk
/usr/share/dpdk/mk/rte.sdkbuild.mk
/usr/share/dpdk/mk/rte.sdkconfig.mk
/usr/share/dpdk/mk/rte.sdkdepdirs.mk
/usr/share/dpdk/mk/rte.sdkdoc.mk
/usr/share/dpdk/mk/rte.sdkexamples.mk
/usr/share/dpdk/mk/rte.sdkgcov.mk
/usr/share/dpdk/mk/rte.sdkinstall.mk
/usr/share/dpdk/mk/rte.sdkroot.mk
/usr/share/dpdk/mk/rte.sdktest.mk
/usr/share/dpdk/mk/rte.shared.mk
/usr/share/dpdk/mk/rte.subdir.mk
/usr/share/dpdk/mk/rte.vars.mk
/usr/share/dpdk/mk/target/generic/rte.app.mk
/usr/share/dpdk/mk/target/generic/rte.vars.mk
/usr/share/dpdk/mk/toolchain/clang/rte.toolchain-compat.mk
/usr/share/dpdk/mk/toolchain/clang/rte.vars.mk
/usr/share/dpdk/mk/toolchain/gcc/rte.toolchain-compat.mk
/usr/share/dpdk/mk/toolchain/gcc/rte.vars.mk
/usr/share/dpdk/mk/toolchain/icc/rte.toolchain-compat.mk
/usr/share/dpdk/mk/toolchain/icc/rte.vars.mk
/usr/share/dpdk/usertools/cpu_layout.py
/usr/share/dpdk/usertools/dpdk-devbind.py
/usr/share/dpdk/usertools/dpdk-pmdinfo.py
/usr/share/dpdk/usertools/dpdk-setup.sh
/usr/share/dpdk/usertools/dpdk-telemetry-client.py
/usr/share/dpdk/x86_64-native-linuxapp-gcc/.config
/usr/share/dpdk/x86_64-native-linuxapp-gcc/app/dpdk-pmdinfogen

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/include/exec-env/rte_kni_common.h
/usr/include/generic/rte_atomic.h
/usr/include/generic/rte_byteorder.h
/usr/include/generic/rte_cpuflags.h
/usr/include/generic/rte_cycles.h
/usr/include/generic/rte_io.h
/usr/include/generic/rte_memcpy.h
/usr/include/generic/rte_pause.h
/usr/include/generic/rte_prefetch.h
/usr/include/generic/rte_rwlock.h
/usr/include/generic/rte_spinlock.h
/usr/include/generic/rte_vect.h
/usr/lib64/libdpdk.so
/usr/lib64/librte_acl.so
/usr/lib64/librte_bbdev.so
/usr/lib64/librte_bitratestats.so
/usr/lib64/librte_bpf.so
/usr/lib64/librte_bus_dpaa.so
/usr/lib64/librte_bus_fslmc.so
/usr/lib64/librte_bus_ifpga.so
/usr/lib64/librte_bus_pci.so
/usr/lib64/librte_bus_vdev.so
/usr/lib64/librte_bus_vmbus.so
/usr/lib64/librte_cfgfile.so
/usr/lib64/librte_cmdline.so
/usr/lib64/librte_common_cpt.so
/usr/lib64/librte_common_dpaax.so
/usr/lib64/librte_common_octeontx.so
/usr/lib64/librte_compressdev.so
/usr/lib64/librte_cryptodev.so
/usr/lib64/librte_distributor.so
/usr/lib64/librte_eal.so
/usr/lib64/librte_efd.so
/usr/lib64/librte_ethdev.so
/usr/lib64/librte_eventdev.so
/usr/lib64/librte_flow_classify.so
/usr/lib64/librte_gro.so
/usr/lib64/librte_gso.so
/usr/lib64/librte_hash.so
/usr/lib64/librte_ip_frag.so
/usr/lib64/librte_jobstats.so
/usr/lib64/librte_kni.so
/usr/lib64/librte_kvargs.so
/usr/lib64/librte_latencystats.so
/usr/lib64/librte_lpm.so
/usr/lib64/librte_mbuf.so
/usr/lib64/librte_member.so
/usr/lib64/librte_mempool.so
/usr/lib64/librte_mempool_bucket.so
/usr/lib64/librte_mempool_dpaa.so
/usr/lib64/librte_mempool_dpaa2.so
/usr/lib64/librte_mempool_octeontx.so
/usr/lib64/librte_mempool_ring.so
/usr/lib64/librte_mempool_stack.so
/usr/lib64/librte_meter.so
/usr/lib64/librte_metrics.so
/usr/lib64/librte_net.so
/usr/lib64/librte_pci.so
/usr/lib64/librte_pdump.so
/usr/lib64/librte_pipeline.so
/usr/lib64/librte_pmd_af_packet.so
/usr/lib64/librte_pmd_ark.so
/usr/lib64/librte_pmd_atlantic.so
/usr/lib64/librte_pmd_avf.so
/usr/lib64/librte_pmd_avp.so
/usr/lib64/librte_pmd_axgbe.so
/usr/lib64/librte_pmd_bbdev_null.so
/usr/lib64/librte_pmd_bnxt.so
/usr/lib64/librte_pmd_bond.so
/usr/lib64/librte_pmd_caam_jr.so
/usr/lib64/librte_pmd_crypto_scheduler.so
/usr/lib64/librte_pmd_cxgbe.so
/usr/lib64/librte_pmd_dpaa.so
/usr/lib64/librte_pmd_dpaa2.so
/usr/lib64/librte_pmd_dpaa2_cmdif.so
/usr/lib64/librte_pmd_dpaa2_event.so
/usr/lib64/librte_pmd_dpaa2_qdma.so
/usr/lib64/librte_pmd_dpaa2_sec.so
/usr/lib64/librte_pmd_dpaa_event.so
/usr/lib64/librte_pmd_dpaa_sec.so
/usr/lib64/librte_pmd_dsw_event.so
/usr/lib64/librte_pmd_e1000.so
/usr/lib64/librte_pmd_ena.so
/usr/lib64/librte_pmd_enetc.so
/usr/lib64/librte_pmd_enic.so
/usr/lib64/librte_pmd_failsafe.so
/usr/lib64/librte_pmd_fm10k.so
/usr/lib64/librte_pmd_i40e.so
/usr/lib64/librte_pmd_ifc.so
/usr/lib64/librte_pmd_ifpga_rawdev.so
/usr/lib64/librte_pmd_ixgbe.so
/usr/lib64/librte_pmd_kni.so
/usr/lib64/librte_pmd_lio.so
/usr/lib64/librte_pmd_netvsc.so
/usr/lib64/librte_pmd_nfp.so
/usr/lib64/librte_pmd_null.so
/usr/lib64/librte_pmd_null_crypto.so
/usr/lib64/librte_pmd_octeontx.so
/usr/lib64/librte_pmd_octeontx_crypto.so
/usr/lib64/librte_pmd_octeontx_ssovf.so
/usr/lib64/librte_pmd_octeontx_zip.so
/usr/lib64/librte_pmd_opdl_event.so
/usr/lib64/librte_pmd_qat.so
/usr/lib64/librte_pmd_qede.so
/usr/lib64/librte_pmd_ring.so
/usr/lib64/librte_pmd_sfc_efx.so
/usr/lib64/librte_pmd_skeleton_event.so
/usr/lib64/librte_pmd_skeleton_rawdev.so
/usr/lib64/librte_pmd_softnic.so
/usr/lib64/librte_pmd_sw_event.so
/usr/lib64/librte_pmd_tap.so
/usr/lib64/librte_pmd_thunderx_nicvf.so
/usr/lib64/librte_pmd_vdev_netvsc.so
/usr/lib64/librte_pmd_vhost.so
/usr/lib64/librte_pmd_virtio.so
/usr/lib64/librte_pmd_virtio_crypto.so
/usr/lib64/librte_pmd_vmxnet3_uio.so
/usr/lib64/librte_port.so
/usr/lib64/librte_power.so
/usr/lib64/librte_rawdev.so
/usr/lib64/librte_reorder.so
/usr/lib64/librte_ring.so
/usr/lib64/librte_sched.so
/usr/lib64/librte_security.so
/usr/lib64/librte_table.so
/usr/lib64/librte_timer.so
/usr/lib64/librte_vhost.so
/usr/share/dpdk/examples/quota_watermark/include/conf.h

%files lib
%defattr(-,root,root,-)
/usr/lib64/librte_acl.so.2.1
/usr/lib64/librte_bbdev.so.1.1
/usr/lib64/librte_bitratestats.so.2.1
/usr/lib64/librte_bpf.so.1.1
/usr/lib64/librte_bus_dpaa.so.2.1
/usr/lib64/librte_bus_fslmc.so.2.1
/usr/lib64/librte_bus_ifpga.so.2.1
/usr/lib64/librte_bus_pci.so.2.1
/usr/lib64/librte_bus_vdev.so.2.1
/usr/lib64/librte_bus_vmbus.so.2.1
/usr/lib64/librte_cfgfile.so.2.1
/usr/lib64/librte_cmdline.so.2.1
/usr/lib64/librte_common_cpt.so.1.1
/usr/lib64/librte_common_dpaax.so.1.1
/usr/lib64/librte_common_octeontx.so.1.1
/usr/lib64/librte_compressdev.so.1.1
/usr/lib64/librte_cryptodev.so.5.1
/usr/lib64/librte_distributor.so.1.1
/usr/lib64/librte_eal.so.9.1
/usr/lib64/librte_efd.so.1.1
/usr/lib64/librte_ethdev.so.11.1
/usr/lib64/librte_eventdev.so.6.1
/usr/lib64/librte_flow_classify.so.1.1
/usr/lib64/librte_gro.so.1.1
/usr/lib64/librte_gso.so.1.1
/usr/lib64/librte_hash.so.2.1
/usr/lib64/librte_ip_frag.so.1.1
/usr/lib64/librte_jobstats.so.1.1
/usr/lib64/librte_kni.so.2.1
/usr/lib64/librte_kvargs.so.1.1
/usr/lib64/librte_latencystats.so.1.1
/usr/lib64/librte_lpm.so.2.1
/usr/lib64/librte_mbuf.so.4.1
/usr/lib64/librte_member.so.1.1
/usr/lib64/librte_mempool.so.5.1
/usr/lib64/librte_mempool_bucket.so.1.1
/usr/lib64/librte_mempool_dpaa.so.1.1
/usr/lib64/librte_mempool_dpaa2.so.2.1
/usr/lib64/librte_mempool_octeontx.so.1.1
/usr/lib64/librte_mempool_ring.so.1.1
/usr/lib64/librte_mempool_stack.so.1.1
/usr/lib64/librte_meter.so.2.1
/usr/lib64/librte_metrics.so.1.1
/usr/lib64/librte_net.so.1.1
/usr/lib64/librte_pci.so.1.1
/usr/lib64/librte_pdump.so.2.1
/usr/lib64/librte_pipeline.so.3.1
/usr/lib64/librte_pmd_af_packet.so.1.1
/usr/lib64/librte_pmd_ark.so.1.1
/usr/lib64/librte_pmd_atlantic.so.1.1
/usr/lib64/librte_pmd_avf.so.1.1
/usr/lib64/librte_pmd_avp.so.1.1
/usr/lib64/librte_pmd_axgbe.so.1.1
/usr/lib64/librte_pmd_bbdev_null.so.1.1
/usr/lib64/librte_pmd_bnxt.so.2.1
/usr/lib64/librte_pmd_bond.so.2.1
/usr/lib64/librte_pmd_caam_jr.so.1.1
/usr/lib64/librte_pmd_crypto_scheduler.so.1.1
/usr/lib64/librte_pmd_cxgbe.so.1.1
/usr/lib64/librte_pmd_dpaa.so.1.1
/usr/lib64/librte_pmd_dpaa2.so.2.1
/usr/lib64/librte_pmd_dpaa2_cmdif.so.2.1
/usr/lib64/librte_pmd_dpaa2_event.so.2.1
/usr/lib64/librte_pmd_dpaa2_qdma.so.2.1
/usr/lib64/librte_pmd_dpaa2_sec.so.2.1
/usr/lib64/librte_pmd_dpaa_event.so.1.1
/usr/lib64/librte_pmd_dpaa_sec.so.1.1
/usr/lib64/librte_pmd_dsw_event.so.1.1
/usr/lib64/librte_pmd_e1000.so.1.1
/usr/lib64/librte_pmd_ena.so.1.1
/usr/lib64/librte_pmd_enetc.so.1.1
/usr/lib64/librte_pmd_enic.so.1.1
/usr/lib64/librte_pmd_failsafe.so.1.1
/usr/lib64/librte_pmd_fm10k.so.1.1
/usr/lib64/librte_pmd_i40e.so.2.1
/usr/lib64/librte_pmd_ifc.so.1.1
/usr/lib64/librte_pmd_ifpga_rawdev.so.1.1
/usr/lib64/librte_pmd_ixgbe.so.2.1
/usr/lib64/librte_pmd_kni.so.1.1
/usr/lib64/librte_pmd_lio.so.1.1
/usr/lib64/librte_pmd_netvsc.so.1.1
/usr/lib64/librte_pmd_nfp.so.1.1
/usr/lib64/librte_pmd_null.so.2.1
/usr/lib64/librte_pmd_null_crypto.so.1.1
/usr/lib64/librte_pmd_octeontx.so.1.1
/usr/lib64/librte_pmd_octeontx_crypto.so.1.1
/usr/lib64/librte_pmd_octeontx_ssovf.so.1.1
/usr/lib64/librte_pmd_octeontx_zip.so.1.1
/usr/lib64/librte_pmd_opdl_event.so.1.1
/usr/lib64/librte_pmd_qat.so.1.1
/usr/lib64/librte_pmd_qede.so.1.1
/usr/lib64/librte_pmd_ring.so.2.1
/usr/lib64/librte_pmd_sfc_efx.so.1.1
/usr/lib64/librte_pmd_skeleton_event.so.1.1
/usr/lib64/librte_pmd_skeleton_rawdev.so.1.1
/usr/lib64/librte_pmd_softnic.so.1.1
/usr/lib64/librte_pmd_sw_event.so.1.1
/usr/lib64/librte_pmd_tap.so.1.1
/usr/lib64/librte_pmd_thunderx_nicvf.so.1.1
/usr/lib64/librte_pmd_vdev_netvsc.so.1.1
/usr/lib64/librte_pmd_vhost.so.2.1
/usr/lib64/librte_pmd_virtio.so.1.1
/usr/lib64/librte_pmd_virtio_crypto.so.1.1
/usr/lib64/librte_pmd_vmxnet3_uio.so.1.1
/usr/lib64/librte_port.so.3.1
/usr/lib64/librte_power.so.1.1
/usr/lib64/librte_rawdev.so.1.1
/usr/lib64/librte_reorder.so.1.1
/usr/lib64/librte_ring.so.2.1
/usr/lib64/librte_sched.so.1.1
/usr/lib64/librte_security.so.1.1
/usr/lib64/librte_table.so.3.1
/usr/lib64/librte_timer.so.1.1
/usr/lib64/librte_vhost.so.4.1
